version: '2'
services:
  redis_1:
    image: redis:3.2-alpine
    container_name: compose_redis
    ports:
      - "6379:6379"
  redis_2:
    image: redis:3.2-alpine
    container_name: compose_redis_2
    ports:
      - "6378:6379"
  mongo_1:
    image: mongo:3.2
    container_name: compose_mongo
    ports:
      - "27017:27017"
  app:
    build: .
    depends_on:
        - redis_1
        - redis_2
        - mongo_1
